image: node:latest
clone:
  depth: full
pipelines:
  branches:
    feature/*:
      - step:
          name: check directory  
          script:
            - /bin/ls  /opt/atlassian/pipelines/agent/build/
      - step:
          name: check directory 
          script:
            -  cd /opt/atlassian/pipelines/agent/build/ 
          
     
