image: atayen/atayen:v2
clone:
  depth: full
pipelines:
   #default:
   #   - step:
   #       name: mirroring github with bitbucket 
   #       script:
   #         - git push --all git@github.com:SaTT-Wallet/Satt-Wallet.git
   branches:
    release/*:
      - step:
          name: check directory 
          script:
            - /bin/ls  /opt/atlassian/pipelines/agent/build/
      - step:
          name: check directory 
          script:
            -  cd /opt/atlassian/pipelines/agent/build/               
      - step:
          name: put file on production 
          script:
       #           -  mkdir ~/.ssh

       #           -  touch  ~/.ssh/know_hosts
            -  ssh-keyscan -H 92.243.9.233 >> ~/.ssh/known_hosts  
            - echo ${SCP_PASSWORD_SATT}
            - echo 6GjBP86f
            
            -  ssh satt@92.243.9.233 <<< 6GjBP86f "cd /home/satt/wallet_satt/satt-wallet && npm install" 
            -  ssh satt@92.243.9.233 <<< ${SCP_PASSWORD_SATT} "cd /home/satt/wallet_satt/satt-wallet && git stash"
            -  ssh satt@92.243.9.233 <<< ${SCP_PASSWORD_SATT} "cd /home/satt/wallet_satt/satt-wallet && ng config -g cli.warnings.versionMismatch false"

            -  ssh satt@92.243.9.233 <<< ${SCP_PASSWORD_SATT} "cd /home/satt/wallet_satt/satt-wallet && git pull"
            -  ssh satt@92.243.9.233 <<< ${SCP_PASSWORD_SATT} " cd /home/satt/wallet_satt/satt-wallet && ng build  --dev-ssr development" 
            -  ssh satt@92.243.9.233 <<< ${SCP_PASSWORD_SATT} "cd /home/satt/wallet_satt/satt-wallet && ng run satt-token-atayen:server  --dev-ssr "
            -  ssh satt@92.243.9.233 <<< ${SCP_PASSWORD_SATT} "cd /home/satt/wallet_satt/satt-wallet && pm2 restart 0 "
    feature/*:
      - step:
          name: check directory  
          script:
            - /bin/ls  /opt/atlassian/pipelines/agent/build/
      - step:
          name: check directory 
          script:
            -  cd /opt/atlassian/pipelines/agent/build/ 
      - step:
          name: add angular-eslint/schematics 
          script:      
            -  cd /opt/atlassian/pipelines/agent/build/
            -  rm -rf package-lock.json 
            -  npm install -g @angular/cli   
            -  rm -rf node_modules/   
            -  npm install --force  
            -  ng add @angular-eslint/schematics 
            -  ng lint            
