image: atayen/atayen:1.0
clone:
  depth: full
pipelines:
  branches:
    release/*:
      - step:
          name: check directory 
          script:
            - /bin/ls  /opt/atlassian/pipelines/agent/build/
      - step:
          name: check directory 
          script:
            -  cd /opt/atlassian/pipelines/agent/build/               
      - step:
          name: put file on production 
          script:
 #           -  mkdir ~/.ssh
          
 #           -  touch  ~/.ssh/know_hosts
            -  ssh-keyscan -H 92.243.9.233 >> ~/.ssh/known_hosts  
            - ssh satt@s26 <<< Q3dHpmCZtw7qsbzhkusW "ls"
            -  sshpass -p ${SCP_PASSWORD_SATT} ssh satt@92.234.9.233  "cd /home/satt/wallet_satt/satt-wallet && git pull"
            -  sshpass -p ${SCP_PASSWORD_SATT} ssh satt@92.234.9.233  "cd /home/satt/wallet_satt/satt-wallet && npm install" 
            -  sshpass -p ${SCP_PASSWORD_SATT} ssh satt@92.234.9.233  "cd /home/satt/wallet_satt/satt-wallet && ng build  " 
            -  sshpass -p ${SCP_PASSWORD_SATT} ssh satt@92.234.9.233  "cd /home/satt/wallet_satt/satt-wallet && ng run satt-token:server"
            -  sshpass -p ${SCP_PASSWORD_SATT} ssh satt@92.234.9.233  "cd /home/satt/wallet_satt/satt-wallet && pm2 restart 0 "
    feature/*:
      - step:
          name: check directory  
          script:
            - /bin/ls  /opt/atlassian/pipelines/agent/build/
      - step:
          name: check directory 
          script:
            -  cd /opt/atlassian/pipelines/agent/build/ 
      - step:
          name: add angular-eslint/schematics 
          script:      
            -  cd /opt/atlassian/pipelines/agent/build/
            -  rm -rf package-lock.json 
            -  npm install -g @angular/cli   
            -  rm -rf node_modules/   
            -  npm install --force  
            -  ng add @angular-eslint/schematics 
            -  ng lint            